### ISSUE TITLE
Add ability to filter sent/received messages

### ISSUE THREAD

**Issue by bnjmn** [niftycode/imessage_reader#11]
Awesome app! Thanks for putting it together. I've been able to access both the excel and sqlite output it creates to look at my messages. My only problem (right now) is that I can't figure out a way to tell if I sent or received the message. I can filter by `sender` to isolate conversations to an individual text thread but without any context it's hard to tell if I sent the message or received it.

You might be able to use the `is_from_me` column on the `message` table in the original database to add a flag or some logic on it. I'm going to keep looking into a little myself but thanks again for putting this together!

**Comment by thecircleisround** [comment]
Addressed in pull request #12 . Pending merge to master.

**Comment by niftycode** [comment]
@bnjmn Thank you! I already had the same idea but didn't find the time to put it into practice.
