### ISSUE TITLE
Allow to select location for chat.db file

### ISSUE THREAD

**Issue by Mac-Lovin** [niftycode/imessage_reader#16]
In its current configuration, the tool goes straight to the default location of the chat.db file. It would be nice to have the ability to select either the default location or a specific folder. This would allow the parsing of a chat.db file that was extracted from a forensic image or another Mac.

**Comment by niftycode** [comment]
That's a good point. I had already thought of such an implementation. So far I haven't had the time to implement this. But this should be possible in a future version.
