### ISSUE TITLE
Make the program available for Linux

### ISSUE THREAD

**Issue by xern** [niftycode/imessage_reader#7]
This program currently only runs on macOS. It would be good if the chat.db file could also be analyzed on other operating systems, perhaps on Linux?

**Comment by niftycode** [comment]
Good idea. Do you want to work on it?

**Comment by GameParrot** [comment]
Speaking of this on Linux, would it be possible to create a server that runs on a Mac that sends and receives iMessages (using AppleScript or Shortcuts) from a client on another Linux machine on the local network?

**Comment by niftycode** [comment]
> Speaking of this on Linux, would it be possible to create a server that runs on a Mac that sends and receives iMessages (using AppleScript or Shortcuts) from a client on another Linux machine on the local network?

Good question. I have no idea. I suspect not, since it would need to be able to access the Message API.

**Comment by GameParrot** [comment]
https://airmessage.org already exists that does something like this

**Comment by niftycode** [comment]
> https://airmessage.org already exists that does something like this

I didn't know about the program before. Thanks for the info.
